name: CI 

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Public Repo
        uses: actions/checkout@v2
        with:
          repository: explicitworkload/helloworld-python
          ref: main

      - name: Print and list out content
        run: |
          pwd
          ls
          cp test.py /home/runner/work/

      - name: Checkout Public Repo
        uses: actions/checkout@v2
        with:
          repository: explicitworkload/python-calculator
          ref: main

      - name: Print and list out content
        run: |
          pwd
          ls
          echo "Echoing work folder"
          ls /home/runner/work/

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.11
      
      # - name: Install dependencies
      #   run: |
      #     pip install pytest pytest-mock robotframework

      # - name: Run pytest
      #   run: pytest -v test_calculator.py 

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create --notes '${{ steps.extract-release-notes.outputs.release_notes }}' --title ${{ github.ref_name }} ${{ github.ref_name }}
        
